POST http://localhost:5000/api/url/shorten 
Content-Type: application/json

{
    "longUrl": "https://www.google.com/search?q=header+name+must+be+a+valid+http+token&oq=header+name+mus&aqs=chrome.0.0i512j69i57.5846j0j7&sourceid=chrome&ie=UTF-8"
}
